# Note: To find out the dependencies for any given version of Rails, look at the
# .../ruby/gems/x.y/specifications/rails-x.y.z.gemspec file
gems:
  - name: rake
    version: '>= 0.7.1'
  - name: activesupport
    version: '= 1.3.1'
  - name: activerecord
    version: '= 1.14.1'
  - name: actionpack
    version: '= 1.12.5'
  - name: actionmailer
    version: '= 1.2.5'
  - name: actionwebservice
    version: '= 1.1.6'
