# Note: To find out the dependencies for any given version of Rails, look at the
# .../ruby/gems/x.y/specifications/rails-x.y.z.gemspec file
defaults:
  install_options: --include-dependencies
gems:
  - name: rake
    version: '>= 0.7.1'
  - name: rails
    version: '= 1.1.6'
