# This config should install all the sample gems
defaults:
  install_options: <%= install_options_for_testing.join(' ') %> -y
  fix_dependencies: true
gems:
  - name: <%= sample_dependent_multilevel_gem_name %>
    version: '>= <%= sample_dependent_gem_version %>'
  - name: <%= sample_dependent_depends_on_multiplatform_gem_name %>
    version: '>= <%= sample_dependent_gem_version %>'
    