gems:
  - name: <%= GemInstaller::SpecUtils.sample_dependent_depends_on_multiplatform_gem_name %>
    version: '>= 1.0.0'
    install_options: <%= GemInstaller::SpecUtils.install_options_for_testing.join(' ') %> -y