defaults:
  install_options: -y
gems:
  # TODO: should pull name and version of file from spec_utils
  # Until then, manually keep this in sync with spec_utils.rb
  - name: stubgem
    version: 1.0.0
    install_options: -y --backtrace --source=http://localhost:9909