gems:
  - name: <%= GemInstaller::SpecUtils.sample_multiplatform_gem_name %>
    version: <%= GemInstaller::SpecUtils.sample_multiplatform_gem_version %>
    platform: mswin32
    install_options: <%= GemInstaller::SpecUtils.install_options_for_testing.join(' ') %>