defaults:
  install_options: -y
gems:
  - name: <%= GemInstaller::SpecUtils.sample_gem_name %>
    version: <%= GemInstaller::SpecUtils::sample_gem_version %>
    install_options: <%= GemInstaller::SpecUtils.install_options_for_testing.join(' ') %>
