<% gem_one_name = "testgem1" %> 
defaults:
  install_options: -y
gems:
  - name: <%= gem_one_name %>
    version: v1.1
    check_for_upgrade: false
  - name: testgem2
    version: v1.2
    install_options: --include-dependencies
