---
# Note: To find out the dependencies for any given version of Rails, 
# use the rubygems 'gem dependency rails' command
defaults:
  install_options: --include-dependencies
gems:
- name: rake
  version: '>= 0.7.1'
- name: rails
  version: '= 1.1.6'
- name: mongrel
  version: '= 1.0.1'
  platform: <%= RUBY_PLATFORM =~ /mswin/ ? 'mswin32' : 'ruby'%>
