  - name: testgem1
    install_options: <%= File.expand_path(File.dirname(__FILE__)) %> <%= FileUtils.pwd %>
<%= include_config("#{File.expand_path(File.dirname(__FILE__))}/../subdir2/included_gem_config2.yml") %>
